#!/bin/sh /etc/rc.common
START=80
start() {
    echo "starting adbyby..."
    /usr/share/adbyby/start-adbyby
}
stop() {
    echo "stopping adbyby..."
     /usr/share/adbyby/stop-adbyby
}
restart() {
    stop
    sleep 1
    start
}
