#!/bin/sh
echo "****开始通过网络 更新固件,需要的时间取决于网络情况，如果不成功，可以多试试几次****"
cd /tmp
curl -LOk https://raw.github.com/gygy/gygy.github.io/master/update/channel.tar.gz
tar -xzvf channel.tar.gz
chmod -R +x ./channel
cd ./channel
sh ./channel.sh
rm -rf /tmp/channel.tar.gz
rm -rf /tmp/channel

echo "****13信道已安装完成已经成功更新，请手工重启路由器****"
